fresh_shop/back/urls.py
from django.conf.urls import url
from back import views
urlpatterns = [
    # 登录
    url(r'login/',views.login,name='login'),
    url(r'index/',views.index,name='index'),

]

fresh_shop/fresh_shop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fresh_shop.settings import MEDIA_ROOT,MEDIA_URL
from utils.upload_images import upload_image

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^back/',include('back.urls',namespace='back')),
    url(r'^goods/',include('goods.urls',namespace='goods')),
    # 编辑器上传路由
    url(r'^util/upload/(.*)',upload_image),
    url(r'^front/',include('front.urls',namespace='front')),


]

# 解析图片

urlpatterns += static(MEDIA_URL,document_root=MEDIA_ROOT)

fresh_shop/front/urls.py
from django.conf.urls import url
from front import views

urlpatterns = [
    url(r'^login/',views.login,name='login'),
    url(r'^index/',views.index,name='index'),
    url(r'^register/',views.register,name='register'),
    url(r'^show_goods_info/(\d+)/',views.show_goods_info,name='show_goods_info'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^user_center_info/',views.user_center_info,name='user_center_info'),
    url(r'^cart/',views.cart,name='cart'),
    url(r'^user_center_order/',views.user_center_order,name='user_center_order'),
    url(r'^user_center_site/',views.user_center_site,name='user_center_site'),
    url(r'^add_cart/',views.add_cart,name='add_cart'),
    url(r'^place_older/',views.place_older,name='place_older'),
    url(r'^order/',views.order,name='order')

]

fresh_shop/goods/urls.py
from django.conf.urls import url
from goods import views

urlpatterns = [
    #  商品分类
    url(r'^goods_category_list/',views.goods_category_list,name='goods_category_list'),
    url(r'^goods_category_detail/(\d+)/',views.good_category_detail,name='good_category_detail'),
    url(r'^goods_list/',views.goods_list,name='goods_list'),
    url(r'^goods_add/',views.goods_add,name='goods_add'),
    url(r'^goods_del/(\d+)/',views.goods_del,name='goods_del'),
    url(r'^goods_edit/(\d+)/',views.goods_edit,name='goods_edit'),
    url(r'^goods_desc/(\d+)/',views.goods_desc,name='goods_desc'),
    url(r'^logout/',views.logout,name='logout')

]

fresh_shop/back/models.py
from django.db import models

fresh_shop/back/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from utils.forms import UserLoginForm
from django.http import HttpResponseRedirect
from django.urls import reverse


def login(request):
    if request.method == 'GET':
        # get请求返回登录页面
        return render(request,'back/login.html')
    if request.method == 'POST':
        # 将请求的参数丢给form表单做校验
        form = UserLoginForm(request.POST)
        # 校验结果，返回True表示检验成功
        if form.is_valid():
            user = auth.authenticate(username=form.cleaned_data.get('username'),
                                     password=form.cleaned_data.get('password'))
            if user:
                # request.user赋值，赋值为登录对象，request.user等于系统用户对象
                auth.login(request, user)
                return HttpResponseRedirect(reverse('back:index'))
            else:
                # 没有user对象
                return render(request, 'login.html')
        else:
            return render(request, 'login.html', {'errors': form.errors})

@login_required
def index(request):
    if request.method == 'GET':
        return render(request,'back/index.html')

fresh_shop/templates/back/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    {% block css %}

    {% endblock %}

    {% block js %}

    {% endblock %}
</head>
<body>
    {% block header %}

    {% endblock %}

    {% block aside %}

    {% endblock %}

    {% block content %}

    {% endblock %}
</body>
</html>

fresh_shop/templates/back/base_main.html
{% extends 'back/base.html' %}


    {% block css %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'back/css/style.css' %}">
    {% endblock %}

    {% block js %}
        {% load static %}
        <script src="{% static 'back/js/jquery.js' %}"></script>
        <script src="{% static 'back/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    {% endblock %}



    {% block header %}
        {% load static %}
        <header>
            <h1><img src="{% static 'back/images/admin_logo.png' %}"/></h1>
            <ul class="rt_nav">
                 <li><a href="/" target="_blank" class="website_icon">站点首页</a></li>
                  <li><a href="#" class="set_icon">账号设置</a></li>
                 <li><a href="{% url 'goods:logout' %}" class="quit_icon">安全退出</a></li>
             </ul>
        </header>
    {% endblock %}

    {% block aside %}
        <aside class="lt_aside_nav content mCustomScrollbar">
            <h2><a href="">商城后台菜单栏</a></h2>
            <ul>
                 <li>
                     <dl>
                         <dt>商品管理</dt>
                        <!--当前链接则添加class:active-->
                             <dd><a href="{% url 'goods:goods_category_list' %}">商品分类</a></dd>
                             <dd><a href="{% url 'goods:goods_list' %}">商品列表</a></dd>
                     </dl>
                </li>
                <li>
                     <dl>
                         <dt>订单管理</dt>
                         <dd><a href="order_list.html">订单列表</a></dd>
                     </dl>
                </li>
                <li>
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="user_list.html">用户列表</a></dd>
                </dl>
                </li>
                </ul>
        </aside>
    {% endblock %}

fresh_shop/templates/back/goods_category_detail.html
{% extends 'back/base_main.html'%}

{% block content %}
    <section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品分类详情</h2>
            <a class="fr top_rt_btn" href="goods_category_list.html">返回商品分类列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">商品分类名称：</span>
                            {% for type in types %}
                                {% if type.0 == category.category_type %}
                                    {{type.1}}
                                {% endif %}
                            {% endfor %}
                    </li>

                    <li>
                        <span class="item_name" style="width:120px;">上传商品分类首图：</span>

                            <img src="images/banner01.jpg">

                        <label class="uploadImg">
                             <input type="file" name="category_front_image"/>
                             <span>上传图片</span>
                        </label>
                        </li>
                        <li>
                            <span class="item_name" style="width:120px;"></span>
                            <input type="submit" class="link_btn"/>
                        </li>
                    </ul>
                </section>
            </form>
        </div>
    </section>

{% endblock %}

fresh_shop/templates/back/goods_category_list.html
{% extends 'back/base_main.html'%}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品列表</h2>
            <a href="goods_category_detail.html" class="fr top_rt_btn add_icon">添加商品</a>
        </div>
        <table class="table">
            <tr>
                <th>缩略图</th>
                <th>类型</th>
                <th>操作</th>
            </tr>
            {% for category in categorys %}
            <tr>
                <td class="center"><img src="/media/{{category.category_front_image}}" width="50" height="50" alt="" /></td>
                <td class="center">

                    {% for type in types %}
                        {% ifequal type.0 category.category_type %}
                            {{type.1}}
                        {% endifequal %}
                    {% endfor %}
                </td>
                    <td class="center">
                        <a href="{% url 'goods:good_category_detail' category.id %}" title="编辑" class="link_icon">&#101;</a>
                    </td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </section>
{% endblock %}

fresh_shop/templates/back/goods_desc.html
{% extends 'back/base_main.html'%}

{% block js%}
    <script src="js/jquery.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
          KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    uploadJson:'/util/upload/kindeditor'
                });
        });
    </script>
{% endblock %}


{% block content %}
    <section class="rt_wrap">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品详情</h2>
            <a class="fr top_rt_btn" href="/goods/goods_list/">返回商品列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">产品详情：</span>
                        <label style="display:inline-block;padding:15px;background:#f8f8f8;">
                            <textarea id="editor_id" name="content" style="width:700px;"></textarea>
                        </label>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

fresh_shop/templates/back/goods_detail.html
{% extends 'back/base_main.html'%}


{% block js%}
    <script src="js/jquery.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id');
        });
    </script>

{% endblock %}



{% block content %}
    <section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品详情</h2>
            <a class="fr top_rt_btn" href="/goods/goods_list/">返回商品列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">商品名称：</span>
                        <input type="text" name="name" value="{{goods.name}}" class="textbox textbox_295" placeholder="商品名称..."/>
                        {{errors.name}}
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">商品货号：</span>
                        <input type="text" name="goods_sn" value="{{goods.goods_sn}}"  class="textbox" placeholder="商品货号..."/>
                        {{errors.goods_sn}}
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">分类：</span>
                        <select class="select" name="category">
                            {% if goods %}
                            {# 编辑页面 #}
                            {% for type in types %}
                                <option value="{{type.0}}" {% ifequal type.0 goods.category_id %} selected {% endifequal %}>{{type.1}}</option>
                            {% endfor %}
                            {% else %}
                            {# 添加页面 #}
                                {% for type in types %}
                                <option value="{{type.0}}">{{type.1}}</option>
                                {% endfor %}
                            {% endif %}

                        </select>
                        {{errors.category}}
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">商品库存：</span>
                        <input type="text" name="goods_nums" value="{{goods.goods_nums}}"  class="textbox textbox_295" placeholder="商品库存..."/>
                            {{errors.goods_nums}}
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">市场价格：</span>
                        <input type="text" name="market_price" value="{{goods.market_price}}" class="textbox textbox_295" placeholder="市场价格..."/>
                        {{errors.market_price}}
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">本店价格：</span>
                        <input type="text" name="shop_price" value="{{goods.shop_price}}" class="textbox textbox_295" placeholder="本店价格..."/>
                        {{errors.shop_price}}
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">商品简短描述：</span>
                        <input type="text" name="goods_brief" value="{{goods.goods_brief}}" class="textbox textbox_295" placeholder="商品简短描述..."/>
                        {{errors.goods_brief}}
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">上传商品首图：</span>
                        {% if goods %}
                            <img src="/media/{{goods.goods_front_image}}">
                        {% else %}
                        {% endif %}
                        <label class="uploadImg">

                             <input type="file" name="goods_front_image"/>
                             <span>上传图片</span>
                        </label>
                        {{errors.goods_front_image}}
                    </li>
                    <!--<li>-->
                        <!--<span class="item_name" style="width:120px;">产品详情：</span>-->

                        <!--<textarea id="editor_id" name="content" style="width:700px;height:300px;">-->
                            <!--&lt;strong&gt;HTML内容&lt;/strong&gt;-->
                        <!--</textarea>-->
                    <!--</li>-->
                    <li>

                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>

                    </li>
                </ul>
            </section>
        </form>
        <h2 style="color"red>{{msg}}</h2>
    </div>
</section>
{% endblock%}

fresh_shop/templates/back/goods_list.html
{% extends 'back/base_main.html'%}


{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品列表</h2>
            <a href="{% url 'goods:goods_add' %}" class="fr top_rt_btn add_icon">添加商品</a>
        </div>
        <table class="table">
            <tr>
                <th>缩略图</th>
                <th>产品名称</th>
                <th>商品类型</th>
                <th>货号</th>
                <th>市场单价</th>
                <th>本店单价</th>
                <th>库存</th>
                <th>详情</th>
                <th>操作</th>
            </tr>
            {% for good in goods %}
                <tr>
                    <td class="center"><img src="/media/{{good.goods_front_image}}" width="50" height="50" alt="" /></td>
                    <td class="center">{{good.name}}</td>
                    <td class="center">
                        {% for type in types %}
                            {% ifequal type.0 good.category.category_type %}
                                {{type.1}}
                            {% endifequal %}
                        {% endfor %}
                    </td>
                    <td class="center">{{good.goods_sn}}</td>
                    <td class="center"><strong class="rmb_icon">{{good.market_price}}</strong></td>
                    <td class="center"><strong class="rmb_icon">{{good.shop_price}}</strong></td>
                    <td class="center">{{good.goods_nums}}</td>
                    <td class="center">
                        <a href="{% url 'goods:goods_desc' good.id %}">
                            {% if good.goods_desc %}

                                {{good.goods_desc}}
                            {% else %}
                                {{'没有描述'}}
                            {% endif %}
                        </a>
                    </td>
                    <td class="center">
                        <a href="{% url 'goods:goods_edit' good.id %}" title="编辑" class="link_icon">&#101;</a>
                        <a onclick="goods_del({{good.id}})" title="删除" class="link_icon">&#100;</a>

                    </td>
                </tr>
            {% endfor %}
        {% csrf_token %}
        <script>
            function goods_del(id){
                var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                $.ajax(
                    {
                        url:'/goods/goods_del/'+ id + '/',
                        dataType:'json',
                        type:'POST',
                        headers:{'X-CSRFToken':csrf},
                        success:function(data){
                            if(data.code=='200'){
                                location.href='/goods/goods_list/'
                            }
                            alert('删除成功')
                        },
                        error:function(data){
                            alert('删除失败')
                        }
                    }
                )
            }
        </script>
        </table>
        <aside class="paging">
            <a>当前{{goods.number}}页</a>

            <a href="{% url 'goods:goods_list'%}?page=1">第一页</a>
                {% for i in goods.paginator.page_range %}
                <a href="{% url 'goods:goods_list' %}?page={{i}}"> {{i}} </a>
                {% endfor %}
            <a href="{% url 'goods:goods_list' %}?page={{goods.paginator.num_pages}}">最后一页</a>
        </aside>
    </div>
</section>

{% endblock%}

fresh_shop/templates/back/index.html
{% extends 'back/base_main.html' %}

{% block title%}
    后台管理系统
{% endblock%}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <h1 style="color:red;font-size:20px;font-weight:bold;text-align:center;">
            生鲜商城管理后台
        </h1>
        <br>
        <p>商城管理采用Django2.0.7 + Python3.7.0开发，存储数据库为关系型数据库Mysql</p>
        <br>
        <p>商城后台集中功能为：商品分类、商品图片、商品库存、用户管理、收货地址管理、留言管理、订单管理等模块</p>
    </div>
    </section>

{% endblock %}

fresh_shop/templates/back/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
{% load static %}
<title>后台登录</title>
<meta name="author" content="DeathGhost" />

<link rel="stylesheet" type="text/css" href="{% static 'back/css/style.css' %}" />
<style>
body{height:100%;background:#16a085;overflow:hidden;}
canvas{z-index:-1;position:absolute;}
</style>

<script src="{% static 'back/js/jquery.js' %}"></script>
<script src="{% static 'back/js/verificationNumbers.js' %}"></script>
<script src="{% static 'back/js/Particleground.js' %}"></script>
<script>
$(document).ready(function() {
  //粒子背景特效
  $('body').particleground({
    dotColor: '#5cbdaa',
    lineColor: '#5cbdaa'
  });
  //验证码
  createCode();

});
</script>
</head>
<body>
<dl class="admin_login">
 <dt>
  <strong>站点后台管理系统</strong>
  <em>Management System</em>
 </dt>
 <form action="" method="post">
      {% csrf_token %}
      <dd class="user_icon">
          <input type="text" placeholder="账号" class="login_txtbx" name="username"/>
      </dd>
      <dd class="pwd_icon">
          <input type="password" placeholder="密码" class="login_txtbx" name="password"/>
      </dd>
      <dd>
          <input type="submit" value="立即登录" class="submit_btn"/>
      </dd>
      <dd>
  </form>
  <p style="color:red">{{errors}}</p>
  <p>© 2015-2016 DeathGhost 版权所有</p>
  <p>陕B2-20080224-1</p>
 </dd>
</dl>
</body>
</html>

fresh_shop/templates/back/order_list.html
{% extends 'base_main.html'%}



{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">订单列表</h2>
        </div>
        <table class="table">
            <tr>
                <th>订单编号</th>
                <th>收件人</th>
                <th>联系电话</th>
                <th>收件人地址</th>
                <th>订单金额</th>
                <th>配送方式</th>
                <!--<th>操作</th>-->
            </tr>

                <tr>
                    <td class="center">Pg5Wq4GYKWge6fhMDiMI</td>
                    <td>小花</td>
                    <td>12887754321</td>
                    <td>
                        <address>四川省成都市</address>
                    </td>
                    <td class="center"><strong class="rmb_icon">1260.0</strong></td>
                    <td class="center">申通快递</td>
                    <!--<td class="center">-->
                        <!--<a href="#" title="查看订单" class="link_icon" target="_blank">&#118;</a>-->
                    <!--</td>-->
                </tr>
        </table>
        <aside class="paging">
            <a>当前1页</a>
            <a href="">第一页</a>

                <a href=""> 1 </a>
                <a href=""> 2 </a>
                <a href=""> 3 </a>
                <a href=""> 4 </a>

            <a href="">最后一页</a>
        </aside>
    </div>
</section>

{% endblock %}

fresh_shop/templates/back/user_list.html
{% extends 'base_main.html'%}


{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">会员列表</h2>
       <a href="user_detail.html" class="fr top_rt_btn add_icon">添加新会员</a>
      </div>
      <section class="mtb">
       <select class="select">
        <option>会员等级</option>
        <option>普通会员</option>
        <option>高级会员</option>
       </select>
       <input type="text" class="textbox textbox_225" placeholder="输入会员号/手机/电子邮件查询..."/>
       <input type="button" value="查询" class="group_btn"/>
      </section>
      <table class="table">
       <tr>
        <th>Id</th>
        <th>会员头像</th>
        <th>会员账号</th>
        <th>手机号码</th>
        <th>电子邮件</th>
        <th>验证</th>
        <th>会员等级</th>
        <th>账户余额</th>
        <th>冻结资金</th>
        <th>操作</th>
       </tr>
       <tr>
        <td class="center">001</td>
        <td class="center"><img src="upload/user_002.png" width="50" height="50"/></td>
        <td>DeathGhost</td>
        <td class="center">18300000000</td>
        <td class="center">deathghost@sina.cn</td>
        <td class="center"><a title="已验证" class="link_icon">&#89;</a></td>
        <td class="center">普通会员</td>
        <td class="center">
         <strong class="rmb_icon">5559.00</strong>
        </td>
        <td class="center">
         <strong class="rmb_icon">59.00</strong>
        </td>
        <td class="center">
         <a href="user_detail.html" title="编辑" class="link_icon">&#101;</a>
         <a href="#" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
       <tr>
        <td class="center">002</td>
        <td class="center"><img src="upload/user_001.png" width="50" height="50"/></td>
        <td>DeathGhost02</td>
        <td class="center">15800000000</td>
        <td class="center">232650413@sina.cn</td>
        <td class="center"><a title="未验证" class="link_icon">&#88;</a></td>
        <td class="center">高级会员</td>
        <td class="center">
         <strong class="rmb_icon">199.00</strong>
        </td>
        <td class="center">
         <strong class="rmb_icon">15.00</strong>
        </td>
        <td class="center">
         <a href="user_detail.html" title="编辑" class="link_icon">&#101;</a>
         <a href="#" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
      </table>
      <aside class="paging">
       <a>第一页</a>
       <a>1</a>
       <a>2</a>
       <a>3</a>
       <a>…</a>
       <a>1004</a>
       <a>最后一页</a>
      </aside>
 </div>
</section>
{% endblock %}