fresh_shop/back/urls.py
from django.conf.urls import url
from back import views
urlpatterns = [
    # 登录
    url(r'login/',views.login,name='login'),
    url(r'index/',views.index,name='index'),

]

fresh_shop/fresh_shop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fresh_shop.settings import MEDIA_ROOT,MEDIA_URL
from utils.upload_images import upload_image

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^back/',include('back.urls',namespace='back')),
    url(r'^goods/',include('goods.urls',namespace='goods')),
    # 编辑器上传路由
    url(r'^util/upload/(.*)',upload_image),
    url(r'^front/',include('front.urls',namespace='front')),


]

# 解析图片

urlpatterns += static(MEDIA_URL,document_root=MEDIA_ROOT)

fresh_shop/front/urls.py
from django.conf.urls import url
from front import views

urlpatterns = [
    url(r'^login/',views.login,name='login'),
    url(r'^index/',views.index,name='index'),
    url(r'^register/',views.register,name='register'),
    url(r'^show_goods_info/(\d+)/',views.show_goods_info,name='show_goods_info'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^user_center_info/',views.user_center_info,name='user_center_info'),
    url(r'^cart/',views.cart,name='cart'),
    url(r'^user_center_order/',views.user_center_order,name='user_center_order'),
    url(r'^user_center_site/',views.user_center_site,name='user_center_site'),
    url(r'^add_cart/',views.add_cart,name='add_cart'),
    url(r'^place_older/',views.place_older,name='place_older'),
    url(r'^order/',views.order,name='order')

]

fresh_shop/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block search %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

</body>
</html>

fresh_shop/templates/web/base_main.html
{% extends 'web/base.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/main.css' %}">
{% endblock %}

{% block js %}
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.js"></script>
{% endblock %}

{% block header %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if user.id %}
                <div class="login_info fl" style="display:inline">
                    欢迎您：<em>{{user.username}}</em>
                    <span>|</span><a href="{% url 'front:logout' %}">注销</a>
                </div>
                {% else %}
                <div class="login_btn fl">
                    <a href="{% url 'front:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'front:register' %}">注册</a>
                </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'front:user_center_info' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'front:cart' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'front:user_center_order' %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block search %}
    <div class="search_bar clearfix">
		<a href="{% url 'front:index' %}" class="logo fl"><img src="{% static 'web/images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'front:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{goods_count}}</div>
		</div>
	</div>
{% endblock %}

{% block footer %}
<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.js"></script>
	<script type="text/javascript" src="{% static 'web/js/slideshow.js' %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

fresh_shop/templates/web/cart.html
{% extends 'web/base_main.html' %}

{% block title %}
	天天生鲜-购物车
{% endblock %}


{% block content %}
<div class="total_count">全部商品<em>2</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	{% if goods %}
	{% for good in goods %}
	<ul class="cart_list_td clearfix" >
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="/media/{{good.0.goods_front_image}}"></li>
		<li class="col03">{{good.0.name}}<br><em>{{good.0.shop_price}}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{good.0.shop_price}}元/500g</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl" onclick="add_number({{good.shop_price}})">+</a>
				<input type="text" class="num_show fl" value="{{good.1}}">
				<a href="javascript:;" class="minus fl" onclick="sub_number({{good.shop_price}})" >-</a>
			</div>
		</li>
		<li class="col07">{{good.2}}</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
	{% endfor %}
	{% endif %}
	<script type="text/javascript">
		function add_number(price){
			<!--修改商品个数和商品的总价-->
			var num = $('.num_show}').val();
			var new_number = parseInt(num) + 1 ;
			var total = price * new_number;
			total = total.toFixed(2)
			$('.total em').html(total + '元');
			<!--修改商品个数-->
			$('.num_show').val(new_number);
		}
	</script>
	<script type="text/javascript">
		function sub_number(price){
			<!--修改商品个数和商品的总价-->
			var num = $('.num_show').val();
			var new_number = parseInt(num) - 1 ;
			if (new_number >= 0){
				var total = price * new_number;
				total = total.toFixed(2)
				$('.total em').html(total + '元');
				<!--修改商品个数-->
				$('.num_show').val(new_number);
			}
		}
	</script>
	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>22</em><br>共计<b>1</b>件商品</li>
		<li class="col04"><a href="{% url 'front:place_older'%}">去结算</a></li>
	</ul>

{% endblock %}



{% block footer %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

fresh_shop/templates/web/detail.html
{% extends 'web/base_main.html' %}

{% block title %}
	天天生鲜-商品详情
{% endblock %}

{% block content %}
	{% load static %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		{% for type in types%}
			{% if goods.category_id == type.0%}
				<a href="#">{{type.1}}</a>
			{% endif %}
		{% endfor %}
		<span>></span>
		<a href="#goodinfo">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/media/{{goods.goods_front_image}}"></div>

		<div class="goods_detail_list fr">
			<h3>{{goods.name}}</h3>
			<p>{{goods.brief}}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{goods.shop_price}}</em></span>
				<span class="show_unit">单  位：500g</span>
				<span class="show_unit">库存：{{goods.goods_nums}}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" onclick="add_number({{goods.shop_price}});" class="add fr">+</a>
					<a href="javascript:;" onclick="sub_number({{goods.shop_price}});" class="minus fr">-</a>
				</div>
			</div>
			<script type="text/javascript">
				function add_number(price){
					<!--修改商品个数和商品的总价-->
					var num = $('.num_show').val();
					var new_number = parseInt(num) + 1 ;
					var total = price * new_number;
					total = total.toFixed(2)
					$('.total em').html(total + '元');
					<!--修改商品个数-->
					$('.num_show').val(new_number);
				}
			</script>
			<script type="text/javascript">
				function sub_number(price){
					<!--修改商品个数和商品的总价-->
					var num = $('.num_show').val();
					var new_number = parseInt(num) - 1 ;
					if (new_number >= 0){
						var total = price * new_number;
						total = total.toFixed(2)
						$('.total em').html(total + '元');
						<!--修改商品个数-->
						$('.num_show').val(new_number);
					}
				}
			</script>
			<div class="total">总价：<em>{{goods.shop_price}}</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart" onclick="add_cart({{goods.id}})">加入购物车</a>
			</div>
			{% csrf_token %}
			<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.js"></script>
			<script type="text/javascript">
				function add_cart(goods_id){
					var goods_num = $('.num_show').val()
					var csrf = $('input[name="csrfmiddlewaretoken"]').val()
					$.ajax({
						url: '/front/add_cart/',
						type:'POST',
						dataType:'json',
						headers:{'X-CSRFToken':csrf},
						data:{'goods_id':goods_id,'goods_num':goods_num},
						success:function(data){
							if (data.code == '200'){
								$('#show_count').html(data.goods_count)
							}
							alert('添加成功')
						},
						error:function(data){
							alert('添加失败')
						}
					})
				}
			</script>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for categoods in categoods_list %}
					<li>
						<a href="{% url 'front:show_goods_info' categoods.id%}"><img src="/media/{{categoods.goods_front_image}}"></a>
						<h4><a href="{% url 'front:show_goods_info' categoods.id%}">{{categoods.name}}</a></h4>
						<div class="prize">{{categoods.shop_price}}</div>
					</li>

					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content" id="goodinfo">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{goods.goods_desc|safe}} </dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}


{% block footer %}
<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<div class="add_jump"></div>

	<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.js"></script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		})
	</script>

{% endblock %}

fresh_shop/templates/web/place_order.html
{% extends 'web/base_main.html' %}

{% block title %}
	天天生鲜-提交订单
{% endblock %}

{% block search %}
{% load static %}
<div class="search_bar clearfix">
		<a href="{% url 'front:index' %}" class="logo fl"><img src="{% static 'web/images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock %}

{% block content %}
	{% load static %}

	
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">11</dd>
		</dl>
		<a href="{% url 'front:user_center_site'%}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">

		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>

		{% for cart in carts %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{forloop.counter}}</li>
			<li class="col02"><img src="/media/{{cart.goods.goods_front_image}}"></li>
			<li class="col03">{{cart.goods.name}}</li>
			<li class="col04">500g</li>
			<li class="col05">{{cart.goods.shop_price}}</li>
			<li class="col06">{{cart.nums}}</li>
			<li class="col07">{{cart.total_price}}元</li>
		</ul>
		{% endfor %}

	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>2</em>件商品，总金额<b>42.60元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>52.60元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>	
{% endblock %}

{% block footer %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
	<script type="text/javascript" src="js/jquery-1.12.2.js"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			localStorage.setItem('order_finish',2);

			$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						window.location.href = 'index.html';
					});	
				},3000)
				
			});
		});

		$.ajax({
			url:'',
			type:'POST',
			dataType:'json',
			success:function(data){

			},
			error:function(data){

			}

		})
	</script>
{% endblock %}

fresh_shop/templates/web/user_center_info.html
{% extends 'web/base_main.html' %}

{% block title%}
	天天生鲜-用户中心
{% endblock %}

{% block content %}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'front:user_center_info'%}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'front:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'front:user_center_site'%}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：{{request.user.username}}</span></li>
							<li><span>联系方式：{{request.user.mobile}}</span></li>
							<li><span>联系地址：{{user.address}}</span></li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<a href="detail.html"><img src="/media/goods/images/goods001.jpg"></a>
					<h4><a href="detail.html">大兴大棚草莓</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/media/goods/images/goods003.jpg"></a>
					<h4><a href="#">吐鲁番梨光杏</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">5.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/media/goods/images/goods002.jpg"></a>
					<h4><a href="#">黄肉桃</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">10.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

			</ul>
		</div>
		</div>
	</div>

{% endblock %}


{% block footer %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

fresh_shop/templates/web/user_center_order.html
{% extends 'web/base_main.html' %}


{% block title %}
	订单中心
{% endblock %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'front:user_center_info'%}" >· 个人信息</a></li>
				<li><a href="{% url 'front:user_center_order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'front:user_center_site'%}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/media/goods/images/goods034.png"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/media/goods/images/goods035.png"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已支付</li>			
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/media/goods/images/goods033.png"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/media/goods/images/goods032.png"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>

{% endblock %}


{% block footer %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

{% endblock %}

fresh_shop/templates/web/user_center_site.html
{% extends 'web/base_main.html' %}

{% block title %}
	天天生鲜-用户中心
{% endblock %}

{% block content %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'front:user_center_info'%}" >· 个人信息</a></li>
				<li><a href="{% url 'front:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'front:user_center_site'%}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>收货人：{{users.signer_name}}</dd>
						<dd>联系手机：{{users.signer_mobile}}</dd>
						<dd>邮编：{{users.signer_postcode}}</dd>
						<dd>收货地址：{{users.address}}</dd>
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="" method="post">
						{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
							{{errors.username}}
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
							<br>
						</div>
						<div align="center">{{errors.addr}}</div>

						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="code">
							{{errors.code}}
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="tel">
							{{errors.tel}}
						</div>

						<input type="submit"  value="提交" class="info_submit">
					</form>

				</div>
		</div>
	</div>

{% endblock %}

{% block footer %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}